# 网络请求地址,访问该网址获取当前的公网ip
public-ip-address-url: https://ifconfig.co/ip

ali:
  # access-key-id 和 access-key-secret 从下面阿里云链接获取
  # https://usercenter.console.aliyun.com/?spm=api-workbench.API%20Explorer.0.0.6e491e0fFtDFOK#/manage/ak
  access-key-id: 
  access-key-secret: 
  # 域名
  domain-name: 
  end-point: alidns.cn-hangzhou.aliyuncs.com